### ISSUE TITLE
Resource Requirements and processing time

### ISSUE THREAD

**Issue by Elliot-Construct** [ais-lab/pl2map#1]
What are the resource requirements and processing time of these examples?

**Comment by thpjp** [comment]
Thank you for your interest in PL2Map. We offer two camera estimation options: point or point+line. If you choose the point option, the processing time will be similar to our previous paper https://thpjp.github.io/d2s/, which depends on the quality of predicted 3D coordinates. On average, the PnP+RANSAC time is 20-40ms, plus 14ms for feedforward of regression network (from RGB image). For more details, please refer to the above work. If you choose the point+line option, it will take more time in PnP+RANSAC, currently around 200ms (similar to Limap). We will report further details on this soon. Resource requirements: we tested on a single GTX 1080ti gpu and i9-9900 cpu.

**Comment by Elliot-Construct** [comment]
Could this process imagery from above?

**Comment by thpjp** [comment]
If you mean the example video results on the webpage, we didn't consider the above processing time, just processed and visualized every frame result and then merged them into those videos.

**Comment by Elliot-Construct** [comment]
I mean from a drone recording video for photogrammetry surveys. Using FLANN matching and SfM and mapping frames imagery to the point cloud to create a texture model currently. The video file has a subtitle file providing gps locations and other camera data (similar to exif data).

Could this be implemented in our pipeline after a fashion?

**Comment by thpjp** [comment]
Yes, of course.

**Comment by Elliot-Construct** [comment]
What file format does it output the point cloud? .laz?

And what is the timeframe on the code release? 👍 

Awesome work by the way! Really enjoyed your paper.

**Comment by thpjp** [comment]
Thank you very much. 
We plan to release everything after the paper's acceptance. 
If everything goes right, the release time is expected around June.
