### ISSUE TITLE
run with camera

### ISSUE THREAD

**Issue by sinais54** [ais-lab/pl2map#5]
Is it possible to run you network online and in real time with a camera?

**Comment by thuanaislab** [comment]
Thank you for your interest. Yes, you can definitely run this method in real time. When using only predicted 3D points the FPS can even reach about 50 FPS. In the case of using both points and lines, the FPS is about 5->15 depending on the quality of predicted 3D coordinates. If you want it as fast as possible, you can sample a low number of 2D-3D correspondences using the predicted uncertain scores before running PnP. However, this might result in a low accuracy.

**Comment by sinais54** [comment]
Thank you very much for your answer
Do you have any code or script to run with the camera or video in your project? Please guide me in this regard.
Thank you

**Comment by thuanaislab** [comment]
I guess, you want to make this works with your own camera and environment. So you need to use [Limap](https://github.com/cvg/limap) to create SfM models of points and lines then use our repo to train a specific pl2map network before running with your camera. You can take a look at the datasets I provided to see how I arranged the training data. 
Unfortunately, I haven't created any script to prepare this step.

**Comment by sinais54** [comment]
Yes, I would like to use your network to work with my camera and environment.
Thank you very much for your response and guidance.
